# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "oar-team/centos7"
    config.vm.hostname = "mysql"
    config.vm.box_download_insecure=true

    config.vm.network :private_network, ip: "10.0.10.50"

    config.ssh.insert_key = false
    config.vm.synced_folder "./", "/vagrant"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

end
